"""
Models for Data Artifacts generated by the FDA Agent.

These artifacts represent structured data outputs from tools that are
persisted in the agent's state for later reference and display.
"""
import uuid
from datetime import datetime
from typing import Literal, Any
from pydantic import BaseModel, Field


# Define literal types for different artifact categories for clarity
ArtifactType = Literal[
    "resolved_entities",
    "manufacturers_list", # Derived from resolved_entities manufacturers
    "product_codes_list", # Derived from resolved_entities product_codes
    "location_context",
    "recall_search_result",
    "event_search_result",
    "clearance_search_result",
    "classification_search_result",
    "udi_search_result",
    "registration_search_result",
    "aggregated_registrations",
]


class DataArtifact(BaseModel):
    """
    Represents a structured data output from a tool, stored as an artifact
    in the agent's session state.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique ID for this artifact")
    type: ArtifactType = Field(description="Category of the data artifact (e.g., 'resolved_entities')")
    description: str = Field(description="Human-readable summary of the artifact's content")
    data: Any = Field(description="The actual structured data payload (e.g., ResolvedEntities model)")
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat(), description="Timestamp of creation")
    tool_name: str = Field(description="Name of the tool that generated this artifact")
    tool_args: dict = Field(default_factory=dict, description="Arguments passed to the tool")

    class Config:
        arbitrary_types_allowed = True # Allow 'data' to be Any type
