name: Bug Report
description: Report a bug or issue with Enhanced FDA Explorer
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI Tool
        - Web UI (Streamlit)
        - REST API (FastAPI)
        - Python SDK
        - OpenFDA Client
        - AI Analysis Engine
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Enhanced FDA Explorer are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Operating system and Python version
      placeholder: "Ubuntu 22.04, Python 3.9.7"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Relevant log output or error messages
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive information)
      render: yaml
      placeholder: |
        environment: development
        debug: true
        # ... (redact sensitive keys)

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context here...