name: Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please be specific about what needs improvement.

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - API Documentation
        - CLI Help
        - Configuration Guide
        - Installation Instructions
        - User Guide
        - Developer Guide
        - Code Comments
        - Examples/Tutorials
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear/confusing
        - Outdated information
        - Typo/grammar
        - Broken links
        - Missing examples
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the problematic documentation located?
      placeholder: "docs/README.md, line 123 or https://example.com/docs/page"
    validations:
      required: true

  - type: textarea
    id: current_content
    attributes:
      label: Current Content
      description: What does the current documentation say? (copy/paste relevant section)
      placeholder: |
        Current text:
        "..."
      render: markdown

  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: What's wrong with the current documentation?
      placeholder: |
        The current documentation is problematic because...
        - It doesn't explain how to...
        - The example shows X but should show Y...
        - The link is broken...
    validations:
      required: true

  - type: textarea
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        The documentation should:
        - Add explanation of...
        - Include example showing...
        - Update the link to...
        - Clarify the section about...

  - type: textarea
    id: user_context
    attributes:
      label: User Context
      description: What were you trying to accomplish when you found this issue?
      placeholder: |
        I was trying to [specific task] when I encountered this documentation issue.
        As a [user type], I expected the documentation to help me [specific goal].

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context or suggestions
      placeholder: Add any other context here...