name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea clearly.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have reviewed the roadmap to see if this is already planned
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - CLI Tool
        - Web UI (Streamlit)
        - REST API (FastAPI)
        - Python SDK
        - OpenFDA Client
        - AI Analysis Engine
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What priority would you assign to this feature?
      options:
        - P1 (High - Core functionality)
        - P2 (Medium - Important enhancement)
        - P3 (Low - Nice to have)
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        As a [user type], I need [functionality] so that [benefit].
        
        Currently, [current limitation or pain point].
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed feature in detail
      placeholder: |
        I would like to see [specific feature/functionality].
        
        This could work by [implementation approach].
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: User Stories
      description: Provide specific user stories or use cases
      placeholder: |
        - As a policy scientist, I want to...
        - As a regulatory analyst, I need to...
        - When using the CLI, I expect to...

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature handles Y edge case
        - [ ] Documentation is updated
        - [ ] Tests are included

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered alternative approaches?
      placeholder: Describe alternative solutions you've considered...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or other relevant information
      placeholder: Add any other context, mockups, or examples here...