# Enhanced FDA Explorer Configuration
app_name: "Enhanced FDA Explorer"
app_version: "1.0.0"
description: "Next-generation FDA medical device data exploration platform"
environment: "development"
debug: false

# OpenFDA API Configuration
openfda:
  base_url: "https://api.fda.gov/"
  api_key: null  # Set via environment variable FDA_API_KEY
  timeout: 30
  max_retries: 3
  rate_limit_delay: 0.5
  user_agent: "Enhanced-FDA-Explorer/1.0"
  verify_ssl: true

# AI Analysis Configuration
ai:
  provider: "openai"  # openai, openrouter, anthropic
  model: "gpt-4"
  api_key: null  # Set via environment variable AI_API_KEY
  base_url: null
  temperature: 0.3
  max_tokens: 2000
  timeout: 60

# Caching Configuration
cache:
  enabled: true
  backend: "memory"  # redis, memory, file
  redis_url: "redis://localhost:6379"
  ttl: 3600  # 1 hour
  max_size: 1000

# Database Configuration
database:
  url: "sqlite:///enhanced_fda_explorer.db"
  echo: false
  pool_size: 10
  max_overflow: 20

# Authentication Configuration
auth:
  enabled: false
  secret_key: "your-secret-key-change-this"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7

# API Server Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"

# Web UI Configuration
webui:
  host: "0.0.0.0"
  port: 8501
  debug: false
  theme: "light"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Monitoring Configuration
monitoring:
  enabled: false
  prometheus_port: 9090
  jaeger_endpoint: null
  log_level: "INFO"

# Application Settings
default_sample_size: 100
max_sample_size: 1000
default_date_range_months: 12
max_date_range_months: 60

# Search Settings
search_timeout: 30
max_concurrent_searches: 5
enable_fuzzy_search: true